apiVersion: "v1"
kind: "Service"
metadata:
  name: "verifier-portal-service"
  namespace: "default"
  labels:
    app: "verifier-portal"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
  selector:
    app: "verifier-portal"
  type: "LoadBalancer"
